osx_image: xcode7.3
sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
  - os: osx
cache:
  directories:
  - node_modules
  - app/node_modules
  - "$HOME/.electron"
addons:
  apt:
    packages:
    - icnsutils
    - graphicsmagick
    - xz-utils
    - rpm
    - wget
    - gcc
    - git
    - mercurial
    - python-dev
    - python-numpy
    - libav-tools
    - libsdl-image1.2-dev
    - libsdl-mixer1.2-dev
    - libsdl-ttf2.0-dev
    - libsmpeg-dev
    - libsdl1.2-dev
    - libportmidi-dev
    - libswscale-dev
    - libavformat-dev
    - libavcodec-dev
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install git-lfs; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git lfs pull; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L https://github.com/github/git-lfs/releases/download/v1.2.0/git-lfs-linux-amd64-1.2.0.tar.gz | tar -xz; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git-lfs-1.2.0/git-lfs pull; fi
install:
- nvm install 6
- npm install npm -g
- npm install electron-builder@next
- npm install
- npm prune
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then scripts/bundlePython.sh; fi
script:
- npm run dist
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
